[audio]
m4a_xq_enable = false
interpolate_fifo = true
resampler = "cosine"
[video]
shader_fs = ""
scale = 2
shader_vs = ""
fullscreen = false

[cartridge]
force_rtc = false
save_type = "detect"

[general]
sync_to_audio = false
bios_skip = false
bios_path = "bios.bin"

